INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (1, 'DERECHA');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (2, 'IZQUIERDA');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (3, 'AMBAS');

