INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (1, 1000000000, 1, 1, 'MALO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (2, 1000001522, 1, 1, 'EL CRACK');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (3, 1000003044, 2, 1, 'EL MANCO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (4, 1000004566, 2, 1, 'VELOZ');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (5, 1000006088, 3, 1, 'LA ARANA');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (6, 1000007610, 3, 1, 'TRES PIERNAS');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (7, 1000009132, 1, 1, 'MALO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (8, 1000010654, 1, 1, 'EL CRACK');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (9, 1000012176, ,3 1, 'EL MANCO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (10, 1000013698, 1, 1, 'VELOZ');

