INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (2, 1, '', '', 1, 1);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (1, 2, '', '', 2, 2);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (4, 0, '', '', 3, 3);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (5, 1, '', '', 1, 1);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (3, 0, '', '', 2, 2);

