INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (1, 2, 'CEDULA CIUDADANIA');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (2, 2, 'CEDULA EXTRANJERIA');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (3, 1, 'REGISTRO CIVIL');

