INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (1, 3, 'SEGUNDA PUNTA');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (2, 3, 'EXTREMO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (3, 4, 'PORTERO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (4, 1, 'DEFENSA CENTRAL');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (5, 1, 'DEFENSA LATERAL');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (6, 2, 'MEDIA PUNTA');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (7, 2, 'MEDIOCENTRO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (8, 2, 'MEDIO CENTRO DEFENSIVO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (9, 3, 'INTERIOR');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (10, 3, 'DELANTERO CENTRO');

