INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('CEDULA');

INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('REGISTRO CIVIL');

INSERT INTO TIPO_DOCUMENTO (DESCRIPCION) VALUES ('TARJETA IDENTIDAD');

INSERT INTO TIPO_TELEFONO (ID_TIPO_TELEFONO, DESCRIPCION) VALUES ('C', 'LVWTPTHVBKWB8JXMDCWM4T3 AA2H74I7XM4WO9QANKXOBDWX8U');

INSERT INTO TIPO_TELEFONO (ID_TIPO_TELEFONO, DESCRIPCION) VALUES ('F', 'RWNKEPXN0  6I0XW 7JE4 4L9MX32UHLATJWJPN06M5R4AV35E');

INSERT INTO TIPO_EMAILS (DESCRIPCION) VALUES ('ESTUDIANTIL');

INSERT INTO TIPO_EMAILS (DESCRIPCION) VALUES ('INSTITUCIONAL');

INSERT INTO TIPO_EMAILS (DESCRIPCION) VALUES ('ESTUDIANTIL');

INSERT INTO TIPO_DIRECCION (DESCRIPCION) VALUES ('CEDULA');

INSERT INTO TIPO_DIRECCION (DESCRIPCION) VALUES ('REGISTRO CIVIL');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('F', 'ENRIQUE', 'DÍAZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'DOMINGO', 'PÉREZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'DOLORES', 'SOTO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'IRMA', 'CONTRERAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'DORA', 'SILVA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ADELA', 'MARTÍNEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ELISA', 'SEPÚLVEDA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ANTONIA', 'MORALES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'DOMINGA', 'RODRÍGUEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'RAMONA', 'LÓPEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'DELIA', 'FUENTES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MAGDALENA', 'HERNÁNDEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'AIDA', 'TORRES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'NICOLAS', 'ARAYA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'HAYDEE', 'FLORES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ROBERTO', 'ESPINOZA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ROSA', 'VALENZUELA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANGEL', 'CASTILLO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ALFREDO', 'TAPIA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JOSÃ© MARIA', 'REYES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MANUELA', 'GUTIÉRREZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ZULEMA', 'CASTRO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'LIDIA', 'PIZARRO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CLARA', 'ÁLVAREZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ISABEL', 'VÁSQUEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ROSARIO', 'SÁNCHEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'RAQUEL', 'FERNÁNDEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'RICARDO', 'RAMÍREZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ERNESTO', 'CARRASCO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ALICIA', 'GÓMEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'PETRONA', 'CORTÉS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'EMMA', 'HERRERA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'GREGORIA', 'NÚÑEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'IRENE', 'JARA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CELIA', 'VERGARA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'EDUARDO', 'RIVERA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'PAULINA', 'FIGUEROA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'PILAR', 'RIQUELME');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CARMELA', 'GARCÍA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CARLOS ALBERTO', 'MIRANDA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'FELISA', 'BRAVO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'FILOMENA', 'VERA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ARMANDO', 'MOLINA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JOSE ANTONIO', 'VEGA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA MAGDALENA', 'CAMPOS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MIGUEL ANGEL', 'SANDOVAL');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'LEONOR', 'ORELLANA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'FELIPE', 'CÁRDENAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA MERCEDES', 'OLIVARES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'NOMBRE', 'ALARCÓN');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA', 'GALLARDO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ROSA', 'ORTIZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JOSE', 'GARRIDO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA LUISA', 'SALAZAR');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CARMEN', 'GUZMÁN');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANA', 'HENRÍQUEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ELENA', 'SAAVEDRA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JUANA', 'NAVARRO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ESTHER', 'AGUILERA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANTONIO', 'PARRA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ELENA', 'ROMERO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'TERESA', 'ARAVENA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANGELA', 'VARGAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARGARITA', 'VÁZQUEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CATALINA', 'CÁCERES');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'FRANCISCO', 'YÁÑEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JUAN', 'LEIVA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'FRANCISCA', 'ESCOBAR');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ELVIRA', 'RUIZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JOSEFA', 'VALDÉS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA ANGELICA', 'VIDAL');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'NELIDA', 'SALINAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'LUISA', 'ZÚÑIGA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANTONIA', 'PEÑA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA TERESA', 'GODOY');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JUAN CARLOS', 'LAGOS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ISABEL', 'MALDONADO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'PEDRO', 'BUSTOS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'LUCIA', 'MEDINA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'SARA', 'PINO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'VICTORIA', 'PALMA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'AMALIA', 'MORENO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'LUIS', 'SANHUEZA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MANUEL', 'CARVAJAL');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MERCEDES', 'NAVARRETE');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JULIA', 'SÁEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'AURORA', 'ALVARADO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ELSA', 'DONOSO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CARLOS', 'POBLETE');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MIGUEL', 'BUSTAMANTE');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'EMILIA', 'TORO');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ANA MARIA', 'ORTEGA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'CONCEPCION', 'VENEGAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'VICENTE', 'LOPEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ALBERTO', 'MENDOZA');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MATILDE', 'GONZÁLEZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'AMELIA', 'MUÑOZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'JOSEFINA', 'ROJAS');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'MARIA DEL CARMEN', 'DÍAZ');

INSERT INTO TIPO_CLIENTE (ID_TIPO_TELEFONO, NOMBRE, APELLIDO) VALUES ('C', 'ENRIQUE', 'PÉREZ');

