INSERT INTO ESTADOS (ID_ESTADO, DESC_ESTADO) VALUES (1, 'INACTIVO');

INSERT INTO ESTADOS (ID_ESTADO, DESC_ESTADO) VALUES (2, 'ACTIVO');

INSERT INTO SEXO (ID_SEXO, ID_ESTADO, DESC_SEXO) VALUES (1, 1, 'FEMENINO');

INSERT INTO SEXO (ID_SEXO, ID_ESTADO, DESC_SEXO) VALUES (2, 1, 'MASCULINO');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (1, 2, 'CEDULA CIUDADANIA');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (2, 2, 'CEDULA EXTRANJERIA');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (3, 1, 'REGISTRO CIVIL');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (1, 'DEFENSA');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (2, 'CENTRO CAMPO');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (3, 'DELATEROS');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (4, 'PORTERO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (1, 3, 'SEGUNDA PUNTA');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (2, 3, 'EXTREMO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (3, 4, 'PORTERO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (4, 1, 'DEFENSA CENTRAL');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (5, 1, 'DEFENSA LATERAL');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (6, 2, 'MEDIA PUNTA');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (7, 2, 'MEDIOCENTRO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (8, 2, 'MEDIO CENTRO DEFENSI');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (9, 3, 'INTERIOR');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (10, 3, 'DELANTERO CENTRO');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (1, 'TECNICO');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (2, 'JUGADOR');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000010000, 1, 2, 1, 'RAQUEL', 'NAVARRO', '', 'CALLE 13 # 112-20', '3318525858', 'NOMBRE@GMAIL.COM', 80, 1.65, '19');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000001522, 1, 1, 1, 'RICARDO', 'AGUILERA', '', 'CARRERA 20 # 15-08', '3318535873', 'MARIA@HOTMAIL.COM', 85, 1.6, '13');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000003044, 2, 1, 2, 'ERNESTO', 'PARRA', '', 'CALLE 13 # 112-20', '3318545888', 'ROSA@HOTMAIL.COM', 60, 1.95, '12');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000004566, 2, 2, 2, 'ALICIA', 'ROMERO', '', 'CARRERA 20 # 15-08', '3318555903', 'JOSE@GMAIL.COM', 100, 1.87, '4');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000006088, 3, 2, 1, 'PETRONA', 'ARAVENA', '', 'CALLE 13 # 112-20', '3318565918', 'NOMBRE@GMAIL.COM', 90, 1.75, '3');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000007610, 3, 2, 1, 'EMMA', 'VARGAS', '', 'CARRERA 20 # 15-08', '3318575933', 'MARIA@HOTMAIL.COM', 80, 1.65, '17');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000009112, 3, 2, 1, 'GREGORIA', 'V�ZQUEZ', '', 'CALLE 13 # 112-20', '3318585948', 'ROSA@HOTMAIL.COM', 85, 1.6, '0');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000010654, 2, 2, 1, 'IRENE', 'C�CERES', '', 'CARRERA 20 # 15-08', '3318595963', 'JOSE@GMAIL.COM', 60, 1.95, '9');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000012176, 1, 2, 1, 'CELIA', 'Y��EZ', '', 'CALLE 13 # 112-20', '3318605978', 'NOMBRE@GMAIL.COM', 100, 1.87, '2');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000013698, 1, 1, 1, 'EDUARDO', 'LEIVA', '', 'CARRERA 20 # 15-08', '3318615993', 'MARIA@HOTMAIL.COM', 90, 1.75, '16');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000015220, 3, 2, 1, 'PAULINA', 'ESCOBAR', '', 'CALLE 13 # 112-20', '3318626008', 'ROSA@HOTMAIL.COM', 80, 1.65, '14');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000016742, 1, 2, 1, 'PILAR', 'RUIZ', '', 'CARRERA 20 # 15-08', '3318636023', 'JOSE@GMAIL.COM', 85, 1.6, '7');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000018264, 3, 2, 1, 'CARMELA', 'VALD�S', '', 'CALLE 13 # 112-20', '3318646038', 'NOMBRE@GMAIL.COM', 60, 1.95, '6');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000019786, 1, 1, 1, 'CARLOS ALBERTO', 'VIDAL', '', 'CARRERA 20 # 15-08', '3318656053', 'MARIA@HOTMAIL.COM', 100, 1.87, '10');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000021308, 1, 2, 1, 'FELISA', 'SALINAS', '', 'CALLE 13 # 112-20', '3318666068', 'ROSA@HOTMAIL.COM', 90, 1.75, '18');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000022830, 2, 2, 1, 'FILOMENA', 'Z��IGA', '', 'CARRERA 20 # 15-08', '3318676083', 'JOSE@GMAIL.COM', 80, 1.65, '1');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000024352, 3, 1, 1, 'ARMANDO', 'PE�A', '', 'CALLE 13 # 112-20', '3318686098', 'NOMBRE@GMAIL.COM', 85, 1.6, '11');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000025874, 2, 1, 1, 'JOSE ANTONIO', 'GODOY', '', 'CARRERA 20 # 15-08', '3318696113', 'MARIA@HOTMAIL.COM', 60, 1.95, '15');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000027396, 1, 2, 1, 'MARIA MAGDALENA', 'LAGOS', '', 'CALLE 13 # 112-20', '3318706128', 'ROSA@HOTMAIL.COM', 100, 1.87, '5');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000028918, 2, 1, 1, 'MIGUEL ANGEL', 'MALDONADO', '', 'CARRERA 20 # 15-08', '3318716143', 'JOSE@GMAIL.COM', 90, 1.75, '8');

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (1, 1000010000);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (2, 1000001522);

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (1, 'DERECHA');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (2, 'IZQUIERDA');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (3, 'AMBAS');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (1, 1000010000, 1, 1, 'MALO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (2, 1000001522, 1, 1, 'EL CRACK');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (3, 1000003044, 2, 1, 'EL MANCO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (4, 1000004566, 2, 1, 'VELOZ');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (5, 1000006088, 3, 1, 'LA ARANA');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (6, 1000007610, 3, 1, 'TRES PIERNAS');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (7, 1000009112, 1, 1, 'MALO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (8, 1000010654, 1, 1, 'EL CRACK');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (9, 1000027396, 3, 1, 'EL MANCO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (10, 1000028918, 1, 1, 'VELOZ');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (0, 'TORNEO 3', 'F0CFSHEHRI0G2RWUEGPUMQE 80QTAWTQN4F8SF6N4H7I6G1U02C46G2S8N29491KX Q3YS0RM9FLX4OIQC VWHMTGA1A1TDC3FO4');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (2, 'TORNEO 1', 'Q7165G99X2EQHT2MEEN7D 11IUIKHL4JMHNX L8LVIJSX3BRK6TJPNGYT1ED67WUFVYUR1V7D48DP1DUPNQ0MMWMELGPXSM74 YO');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (1, 'TORNEO 2', 'C03CSGY9683H5SOQ9VSL3NUBAEQUEU0KMAWA9U BOMUF1K2D 9GHXQRJ4444POX2238COXAHCB9OOK55SLULYJ6OBFSWW283B191');

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (2, 1, '', '', 1, 1);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (1, 2, '', '', 2, 2);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (4, 0, '', '', 3, 3);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (5, 1, '', '', 1, 1);

INSERT INTO PARTIDOS (ID_PARTIDO, ID_TORNEO, FECHA_PARTIDO, HORA_PARTIDO, ID_EQUIPO_GANADOR, ID_EQUIPO_PERDEDOR) VALUES (3, 0, '', '', 2, 2);

--INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, ID_PARTIDO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (4, 1000010000, 1, , 'MILLONARIOS', ' JXB30JPJT9WT3L5JA 1TMY9EX3 6U BHC9BVOH8FESY6JCIVRV3SPL4Q4EYN9YDNENWDH6WWSUN8A3CWPTLLQTO6QSYB685MUB1');

--INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, ID_PARTIDO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (2, 1, 1, 3, 'SANTA FE', 'S1LAF9K41JBR03LYTBDX3JPXMSWHD Y0A NQP8MVV0VVKJ5PEF4DQ XNG7LV HK5D1FLYK OMCWD0YSFE9JN1OLQ5PRO869N0BRU');

--INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, ID_PARTIDO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (1, 1, 1, 2, 'NAIONAL', 'IUJ BTQDR8QG5PR1UVPJQ5ECA6UGS 93Y00IBXO3WFSJPPRB1 MOWJMUYFIBG2QG7MCO 1IG0KGTQ1SN2AXPC49MSTK6ER18093H');

--INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, ID_PARTIDO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (3, 1, 3, 2, 'TOLIMA', 'MQH 5JGS90OIM2JVS1IRJLU6CKP3QRKKC1P7MYI04PYUY1NFCRTCALKNRA7DO5QAAULCARWUW1PDLM5FQEYW5POW0EPOP2P24G9K');

--INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, ID_PARTIDO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (5, 1, 3, 1, 'AMERICA', 'NLILE PYKRB4MCF7FBJNM4KP5H3MNA 3R3KJ41P7NY0985I3MNMOCHRMC5RFR88COFHM23C99SMA7H7PR5BEVQH39N7XBYTBB5SW');

