INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (1, 'DEFENSA');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (2, 'CENTRO CAMPO');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (3, 'DELATEROS');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (4, 'PORTERO');

