INSERT INTO ESTADOS (ID_ESTADO, DESC_ESTADO) VALUES (1, 'INACTIVO');

INSERT INTO ESTADOS (ID_ESTADO, DESC_ESTADO) VALUES (2, 'ACTIVO');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (1, 'TECNICO');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (2, 'JUGADOR');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (3, 'TECNICO');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (4, 'JUGADOR');

INSERT INTO TIPO_USUARIO (ID_TIPO_USUARIO, DESC_TIPO_USUARIO) VALUES (5, 'TECNICO');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (1, 'DELATEROS');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (2, 'PORTERO');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (3, 'DEFENSA');

INSERT INTO TIPO_POSICIONES_TERRENO (ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_TERRENO) VALUES (4, 'CENTRO CAMPO');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (1, 'AMBAS');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (2, 'DERECHA');

INSERT INTO TIPO_PIERNA_HABIL (ID_PIERNA_HABIL, DESC_PIERNA_HABIL) VALUES (3, 'IZQUIERDA');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (2, 'TORNEO 3', '2O9 7221PJOP0SH1T0NGA73N FJC2S549VA71QQQ1F0EWGT YPENTS5HINB01TM6J97A5BOW7U3D02PVQ2A C3B4KH63GLX2H VH');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (3, 'TORNEO 1', 'E5VQ6CP1CYT3BOPGEB0RH8028EMBWY0TE1LMVFNA8OB13ELNLVF T7XXC404LES10UW4NRXWOMTO3O18V41WUWP7BPBFFF2L53CH');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (4, 'TORNEO 2', 'IMRROA1NA47CVIQATV2GI80QK WT WN1WVSW5GP3H TFL AOSN4SYO3BAEPY0 AV2V8MVUHHXF X6YB6MGG22HUOF181GECE4RCJ');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (1, 'TORNEO 3', 'SGSEPPRHAE3LA2XY5EM 8NKVWK0W60KU21XU YSDJRGV5IHPIIAL8RXR7JLFLAT5UQ5AWK1AM6L Y4HMN74UUSJPDY1JPVO7SH8T');

INSERT INTO TORNEOS (ID_TORNEO, NOMBRE_TORNEO, RUTA_IMAGEN) VALUES (0, 'TORNEO 1', 'AEQOSF UOXBW85E RA7KVDRYB615ODWMGK3NFNH ICGFCIIUEIJVGVUDMJ15VBBJTEKNFT2OSWXHC LBOC0F UKJP54IF2D7H5UY');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (1, 1, 'INTERIOR');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (2, 1, 'DELANTERO CENTRO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (3, 2, 'SEGUNDA PUNTA');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (4, 2, 'EXTREMO');

INSERT INTO TIPO_POSICIONES_JUGADOR (ID_TIPO_POSICION_JUGADOR, ID_TIPO_POSICION_TERRENO, DESC_TIPO_POSICION_JUGADOR) VALUES (5, 3, 'PORTERO');

INSERT INTO SEXO (ID_SEXO, ID_ESTADO, DESC_SEXO) VALUES (1, 1, 'FEMENINO');

INSERT INTO SEXO (ID_SEXO, ID_ESTADO, DESC_SEXO) VALUES (2, 1, 'MASCULINO');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (1, 1, 'TARJETA IDENTIDAD');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (2, 1, 'CEDULA CIUDADANIA');

INSERT INTO DOCUMENTO_IDENTIDAD (ID_DOCUMENTO, ID_ESTADO, DESC_DOCUMENTO) VALUES (3, 2, 'CEDULA EXTRANJERIA');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000000000, 1, 1, 1, 'ANTONIO', 'FERN�NDEZ', '1335-1-13 6:3:23', 'CARRERA 20 # 15-08', '3318525858', 'JOSE@GMAIL.COM', 90, 1.75, '3');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000001522, 1, 1, 1, 'ELENA', 'RAM�REZ', '1-1-1 0:0:0', 'CALLE 13 # 112-20', '3318535873', 'NOMBRE@GMAIL.COM', 80, 1.65, '1');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000003044, 2, 2, 2, 'TERESA', 'CARRASCO', '367-10-16 1:26:9', 'CARRERA 20 # 15-08', '3318545888', 'MARIA@HOTMAIL.COM', 85, 1.6, '2');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000004566, 2, 2, 2, 'ANGELA', 'G�MEZ', '901-5-27 3:6:40', 'CALLE 13 # 112-20', '3318555903', 'ROSA@HOTMAIL.COM', 60, 1.95, '3');

INSERT INTO USUARIO (NUMERO_DOCUMENTO, ID_DOCUMENTO, ID_SEXO, ID_TIPO_USUARIO, NOMBRE_, APELLIDO, FECHANACIMIENTO, DIRECCION, TELEFONO, EMAIL, PESO, ESTURA, RUTA_FOTO) VALUES (1000006088, 3, 1, 3, 'MARGARITA', 'CORT�S', '1603-9-26 7:12:38', 'CARRERA 20 # 15-08', '3318565918', 'JOSE@GMAIL.COM', 100, 1.87, '1');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (1, 1000000000, 1, 1, 'LA ARANA');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (2, 1000001522, 1, 1, 'TRES PIERNAS');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (3, 1000003044, 2, 3, 'MALO');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (4, 1000004566, 2, 2, 'EL CRACK');

INSERT INTO JUGADOR (ID_JUGADOR, NUMERO_DOCUMENTO, ID_PIERNA_HABIL, ID_TIPO_POSICION_JUGADOR, APODO) VALUES (5, 1000006088, 3, 2, 'EL MANCO');

--INSERT INTO MINUTOS (ID_REGISTRO_MINUTOS, ID_PARTIDO, ID_JUGADOR, CANTIDAD_MINUTOS_JUGADOS) VALUES (4, 0, 1, 0);

--INSERT INTO MINUTOS (ID_REGISTRO_MINUTOS, ID_PARTIDO, ID_JUGADOR, CANTIDAD_MINUTOS_JUGADOS) VALUES (0, 2, 2, 4);

--INSERT INTO MINUTOS (ID_REGISTRO_MINUTOS, ID_PARTIDO, ID_JUGADOR, CANTIDAD_MINUTOS_JUGADOS) VALUES (2, 4, 3, 2);

--INSERT INTO MINUTOS (ID_REGISTRO_MINUTOS, ID_PARTIDO, ID_JUGADOR, CANTIDAD_MINUTOS_JUGADOS) VALUES (1, 1, 4, 1);

--INSERT INTO MINUTOS (ID_REGISTRO_MINUTOS, ID_PARTIDO, ID_JUGADOR, CANTIDAD_MINUTOS_JUGADOS) VALUES (3, 3, 5, 3);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (1, 1000000000);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (2, 1000000000);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (3, 1000001522);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (4, 1000001522);

INSERT INTO TECNICO (ID_TECNICO, NUMERO_DOCUMENTO) VALUES (5, 1000003044);

INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (2, 1, 1, 'AMERICA', '6XR3IBOC0HO7W5JHIQRDT30W92ON0BQG2NP 5U0HI ES0OQI7CX0DWWY45M08A VFGI96SJGHFBHMINVC0A5P4 9JQGGPOLX5XWP');

INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (0, 3, 1, 'CALI', 'RC7L0D89DASBX2W9O0JORB59X8Y76N4XGHA17C77F3TBHR4JAKYEHSF0 CHHE4G3KTKP7KH3TCMA3W1Q92FIV2P4FG7IXHKTYXO6');

INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (4, 3, 2, 'MILLONARIOS', '2RP1M6RKJ8Q2BVOT35CR0MULRUI676865U4CS9UNYP62JTA5G5FW5N2HIYELB4WV4HRUI12ISDJ2ODGRHATX57QY66N35KKCCLPI');

INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (1, 3, 2, 'SANTA FE', 'QRNQY GSXJQI NC1C9XYKOQ5TUSCJKOWEI4KU3NB7IQU5VWXUXC VDYEH7AC6SH70ARFTJ4OUCN18D51MGSWMHMM9SXWQ41RL0QY');

INSERT INTO EQUIPO (ID_EQUIPO, ID_JUGADOR, ID_TECNICO, NOMBRE_EQUIPO, RUTA_ESCUDO) VALUES (3, 3, 3, 'NAIONAL', '1LF5YO29DYKUILNI1K02TTX3SWHQA51X0J7FNU22AD1N1JTE9TVBA45X7C78F3MX0RBTSR4AEHY70OPC U3BCXDM3CMPFY0MEE6G');

