INSERT INTO BANCO.TIPO_DOCUMENTO
(ID_TIPO_DOCUMENTO, DESCRIPCION)
VALUES(1, 'Cedula');
INSERT INTO BANCO.TIPO_DOCUMENTO
(ID_TIPO_DOCUMENTO, DESCRIPCION)
VALUES(2, 'Registro Civil');
INSERT INTO BANCO.TIPO_DOCUMENTO
(ID_TIPO_DOCUMENTO, DESCRIPCION)
VALUES(3, 'Tarjeta Identidad');
INSERT INTO BANCO.TIPO_DOCUMENTO
(ID_TIPO_DOCUMENTO, DESCRIPCION)
VALUES(4, 'Otro');